### ISSUE TITLE
[BUG] Error on increasing "Maximum Prompt Size" above 1,024: "java.io.IOException: Bad request (400)"

### ISSUE THREAD

**Issue by cyrilshaji38** [aress31/burpgpt#11]
# Description

Error thrown when increasing "Maximum Prompt Size" above 1,024 in the extension settings. The full error can be seen in the error section below.

# Steps to Reproduce

1. Go to 'BurpGPT Settings'>'OpenAI API'
2. Enter a valid openAI API key
3. Select any model
4. Set 'Maximum Prompt Size' as 2,048
5. Use the default prompt
6. Click on 'Apply'
7. Run passive scan on a request

# Expected Behavior

Expected larger prompts to work since most requests and responses collectively cross 1,024 characters. 

# Error

BurpGPT: 
java.io.IOException: Bad request (400):{
"error":{
"message": "This model's maximum context length is 2049 tokens, however you requested 2796 tokens (748 in your prompt; 2048 for the completion). Please reduce your prompt or completion length.",
"type": "invalid_request_error",
"param": null,
 "code": null
}
}

# Environment

- OS: Windows
- Java version: 11
- GPT model used: GPT-3
- Maximum tokens used: 2048
- Prompt used: Default prompt from extension

**Comment by aress31** [comment]
This is normal, GPT-3 models are limited to 2048 tokens (request + completion) hence the reason why I added an option to fine tune the request  max token length. Closing the ticket for now.
