### ISSUE TITLE
[BUG]"java.IOException:Too many requests(429)" error occurred during usage, but my traffic is normal!!

### ISSUE THREAD

**Issue by KOG-3301** [aress31/burpgpt#13]
Hi,

I encountered an issue while using Burp GPT. When I attempted to run the tool, I received an error message that read "java.io.IOException: Unauthorized (401)". I have checked my request settings and made sure that I have the necessary authentication credentials, but the error persists.

Steps to reproduce the issue:

1.Install and open Burp Suite.
2.Load the GPT extension and configure the necessary settings.
3.Run the tool and observe the error message.
Expected result:

The tool should run without error.

Actual result:

The tool returns an error message that reads "java.io.IOException: Unauthorized (429)".

Additional information:

This is the current traffic for my OpenAI API.

![ec2_24](https://user-images.githubusercontent.com/75877456/233568336-c72ea9c2-2546-4968-ae8e-b790d3371f55.png)

1.I have checked my authentication settings and verified that they are correct.
2.I have attempted to run the tool multiple times with the same result.
3.This issue occurs consistently, and I have not been able to successfully run the tool.
Please let me know if there is any additional information that I can provide. Thank you for your help in resolving this issue.

**Comment by aress31** [comment]
You ran out of credit and need to buy more to use the openai api.

**Comment by KOG-3301** [comment]
> 需

However, I still have about $17 of traffic left in the above picture, and I didn't use the OpenAI API before using this package. Do I need to do any settings when scanning?

**Comment by KOG-3301** [comment]
> You ran out of credit and need to buy more to use the openai api.

Sorry, this is my first time using an external API to connect to Burp Suite.
I may ask some basic questions.

**Comment by aress31** [comment]
@KOG-3301 you can see on the picture that you shared that your credit has expired hence the error message from burpgpt. Hope this helps.  🙃

**Comment by KOG-3301** [comment]
Got it. Thanks for your answer.<3
