### ISSUE TITLE
[BUG] <title> Prompts the model for deprecation

### ISSUE THREAD

**Issue by 0a00** [aress31/burpgpt#27]
### Prerequisites

- [X] Thoroughly read the [README file](https://github.com/aress31/burpgpt/blob/main/README.md).
- [X] Checked the [project requirements](https://github.com/aress31/burpgpt#requirements) and ensured they are met.
- [X] Searched for existing issues that may address the problem.
- [X] Performed basic troubleshooting steps.

### Description

Prompts the model for deprecation

### Steps to Reproduce

Prompts the model for deprecation

### Expected Behavior

Prompts the model for deprecation

### Environment

- OS: [ Linux]
- Java version: [e.g. 8, 11, 16]
- Burp Suite version: [e.g. Professional 2021.4, Community 2021.4]
- GPT model used: [e.g. GPT-3, GPT-Neo, GPT-2]
- Maximum tokens used: [e.g. 2048]
- Prompt used: [e.g. "Analyze the following HTTP request and response for potential vulnerabilities..."]

### Error Message

Prompts the model for deprecation

### Additional Context

Prompts the model for deprecation

**Comment by tatsumaki002** [comment]
Ran into the same problem.

**Comment by tatsumaki002** [comment]
well,**the creator will no longer maintain this repository.**

**Comment by xelerated** [comment]
The creator also claims there is no "community" edition and to "read the site" which still shows.... A COMMUNITY EDITION, so moral of the story is, find something else, dont give them money.

**Comment by ranhn** [comment]
提示模型弃用，如何更新模型

**Comment by aress31** [comment]
https://burpgpt.app/#pricing
