### ISSUE TITLE
[BUG] gradle error building plugin

### ISSUE THREAD

**Issue by xelerated** [aress31/burpgpt#28]
### Prerequisites

- [X] Thoroughly read the [README file](https://github.com/aress31/burpgpt/blob/main/README.md).
- [X] Checked the [project requirements](https://github.com/aress31/burpgpt#requirements) and ensured they are met.
- [X] Searched for existing issues that may address the problem.
- [X] Performed basic troubleshooting steps.

### Description

I get an error running the gradlew shadowJar command,
FAILURE: Build failed with an exception.

* Where:
Build file '/home/griff/Downloads/burpgpt/lib/build.gradle' line: 62

Line 62:     def cmd = 'git describe --tags --always --dirty=-SNAPSHOT'.execute()

### Steps to Reproduce

sudo ./gradlew shadowJar

### Expected Behavior

Builds plugin

### Environment

- OS: Linux
- Java version: openjdk 17.0.10 2024-01-16
- Burp Suite version: Professional latest version
- GPT model used: GPT-3 but not that far yet
- Maximum tokens used: N/A
- Prompt used: N/A

**Comment by xelerated** [comment]
So i took out the offending section from the build.gradle and get this

└─$ sudo ./gradlew shadowJar
Invalid Java installation found at '/usr/lib/jvm/openjdk-17' (Common Linux Locations). It will be re-checked in the next build. This might have performance impact if it keeps failing. Run the 'javaToolchains' task for more details.
> Task :lib:generateMainEffectiveLombokConfig1 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':lib:generateMainEffectiveLombokConfig1'.
> A problem occurred starting process 'command '/usr/lib/jvm/java-17-openjdk-amd64/bin/java''

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
1 actionable task: 1 executed

**Comment by tatsumaki002** [comment]
Maybe u need use the gradle Ver 8.1.1 as the same with this project

**Comment by xelerated** [comment]
Where does it show in what i pasted what gradle version im using?

**Comment by xelerated** [comment]
Since no one replied to the last one.
