### ISSUE TITLE
[BUG] <titl在哪里配置api key呢e>

### ISSUE THREAD

**Issue by ranhn** [aress31/burpgpt#30]
### Prerequisites

- [X] Thoroughly read the [README file](https://github.com/aress31/burpgpt/blob/main/README.md).
- [X] Checked the [project requirements](https://github.com/aress31/burpgpt#requirements) and ensured they are met.
- [X] Searched for existing issues that may address the problem.
- [X] Performed basic troubleshooting steps.

### Description

未找到在哪里配置api key相关的页面

### Steps to Reproduce

1

### Expected Behavior

1

### Environment

- OS: [e.g. Windows, macOS, Linux]
- Java version: [e.g. 8, 11, 16]
- Burp Suite version: [e.g. Professional 2021.4, Community 2021.4]
- GPT model used: [e.g. GPT-3, GPT-N呃呃eo, GPT-2]
- Maximum tokens used: [e.g. 2048]
- Prompt used: [e.g. "Analyze the following HTTP request and response for potential vulnerabilities..."]

**Comment by aress31** [comment]
https://burpgpt.app/#pricing
