### ISSUE TITLE
[BUG] Brief description of the issue

### ISSUE THREAD

**Issue by oakkaya** [aress31/burpgpt#5]
i have this error in my burp extension errors tab after i installed extension :(

```
java.lang.NoSuchMethodError: 'burp.api.montoya.ui.menu.BasicMenuItem burp.api.montoya.internal.MontoyaObjectFactory.basicMenuItem(java.lang.String)'
	at burp.api.montoya.ui.menu.BasicMenuItem.basicMenuItem(BasicMenuItem.java:39)
	at burpgpt.gui.MyMenu.createMenu(MyMenu.java:10)
	at burp.MyBurpExtension.initialize(MyBurpExtension.java:58)
	at burp.lji.l(Unknown Source)
	at burp.m2t.V(Unknown Source)
	at burp.m2r.lambda$initialiseOnNewThread$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by Teicu** [comment]
yo,why open another report since others have reported the same problem?

**Comment by rizaust** [comment]
+1

**Comment by crypto-maniac** [comment]
also same with last Burp version 2023.2.4

> java.lang.NoSuchMethodError: 'burp.api.montoya.ui.menu.BasicMenuItem burp.api.montoya.internal.MontoyaObjectFactory.basicMenuItem(java.lang.String)'
> 	at burp.api.montoya.ui.menu.BasicMenuItem.basicMenuItem(BasicMenuItem.java:39)
> 	at burpgpt.gui.MyMenu.createMenu(MyMenu.java:10)
> 	at burp.MyBurpExtension.initialize(MyBurpExtension.java:58)
> 	at burp.jfw.D(Unknown Source)
> 	at burp.g5b.u(Unknown Source)
> 	at burp.g5g.lambda$initialiseOnNewThread$0(Unknown Source)
> 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
> 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
> 	at java.base/java.lang.Thread.run(Thread.java:833)
>

**Comment by aress31** [comment]
The issue template is there for a reason...

Which version of the plugin do you use, what's your environment... please fill out the issue template then I will be able to assist.

**Comment by HB666666** [comment]
I feel that the latest version of burpsuite is needed, and I also reported an error on the 2023 2 version
![image](https://user-images.githubusercontent.com/110554291/231063303-537b7f4d-9f6c-4c3e-a838-4c178eec685a.png)

**Comment by oakkaya** [comment]
> The issue template is there for a reason... OP didn't even bothered changing the issue name...
> 
> Which version of the plugin do you use, what's your environment... please fill out the issue template then I will be able to assist.

It gives the corresponding error in version 2023.2. In version 2023.3.2 this was not a problem and the plugin worked.

![image](https://user-images.githubusercontent.com/5351581/231100957-40e4ef3f-af1e-4dbf-8050-d8cd5b83d842.png)
